program: tools/train_cat_labelme.py
method: bayes
name: cat_kidney_sweep
command:
  - ${env}
  - python
  - ${program}
  - "--colab"
  - "--all_images"
  - "--backbone"
  - "resnet152"
  - "--wandb"
  - "--num_epochs"
  - "50"
  - ${args}
metric:
  name: mAP
  goal: maximize
parameters:
  # roi_heads_score_thresh:
  #   values: [0.6] # [0.6, 0.9]
  rpn_bg_iou_thresh:
    min: 0.1
    max: 0.3
    distribution: uniform
  rpn_fg_iou_thresh:
    min: 0.85
    max: 0.95
    distribution: uniform
  # roi_heads_nms_thresh:
  #   values: [0.3, 0.4]  # [0.3, 0.6]
  # learning_rate:
  #   min: 0.00002
  #   max: 0.0002
  #   distribution: log_uniform
  # roi_heads_score_thresh:
  #   min: 0.3
  #   max: 0.7
  #   distribution: uniform
  # score_thresh:
  #   min: 0.5
  #   max: 0.8
  #   distribution: uniform
  # batch_size:
  #   values: [4, 8]
  lr_decrease_ratio:
    min: 50
    max: 1000
    distribution: uniform
