program: train_cat_labelme.py
method: bayes
name: cat_kidney_sweep_brightness_contrast
command:
  - ${env}
  - python
  - ${program}
  - "--colab"
  - "--all_images"
  - "--backbone"
  - "resnet152"
  - "--wandb"
  - "--num_epochs"
  - "40"
  - ${args}
metric:
  name: mAP
  goal: maximize
parameters:
  brightness_min:
    min: 0.3
    max: 0.7
    distribution: uniform
  brightness_max:
    min: 1.3
    max: 1.7
    distribution: uniform
  contrast_min:
    min: 0.3
    max: 0.7
    distribution: uniform
  contrast_max:
    min: 1.3
    max: 1.7
    distribution: uniform
