program: train_cat_labelme.py
method: bayes
name: cat_kidney_sweep_brightness_contrast_rpn_nms
command:
  - ${env}
  - python
  - ${program}
  - "--colab"
  - "--all_images"
  - "--backbone"
  - "resnet152"
  - "--wandb"
  - "--num_epochs"
  - "25"
  - "--learning_rate"
  - ".0002"
  - ${args}
metric:
  name: mAP
  goal: maximize
parameters:
  rpn_nms_thresh:
    min: 0.3
    max: 0.9
    distribution: uniform
